import React from "react";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

console.log(
  'env.SENSITIVE_INFORMATION:',
  process.env.SENSITIVE_INFORMATION,
)

const lato = Lato({
  weight: ['400'],
  style: ['normal'],
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "DevelopsToday Test Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main className="
          max-w-3xl h-full
          flex flex-col justify-start items-stretch
          mx-auto px-12 py-6 my-6 gap-4
          bg-gray-100 rounded-3xl overflow-hidden
        ">
          {children}
        </main>
      </body>
    </html>
  );
}
